---
- name: open fleet port for nodes
  hosts: nodes
  tasks:
  - name: open port 8220 in firewalld for agents
    firewalld:
      port: 8220/tcp
      permanent: true
      state: enabled
      immediate: true
  - name: restart firewalld
    service:
      name: firewalld
      state: restarted


