---
- name: setup kibana
  hosts: localhost
  vars:
    packages:
      - name: elasticsearch
        description: elasticsearch-repo
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: no
      - name: kibana
        description: kibana-repo
        baseurl: https://artifacts.elastic.co/packages/8.x/yum
        gpgcheck: yes
        gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        enabled: no
  tasks:
  - name: import rpm key
    rpm_key:
      state: present
      key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  - name: create repos
    yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      baseurl: "{{ item.baseurl }}"
      enabled: "{{ item.enabled }}"
      gpgcheck: "{{ item.gpgcheck }}"
      gpgkey: "{{ item.gpgkey }}"
      state: present
    loop: "{{ packages }}"
  - name: install packages
    yum:
      name: "{{ item.name }}"
      state: present
      enablerepo: "{{ item.name }}"
    loop: "{{ packages }}"
  - name: open firewall ports for services
    firewalld:
      port: "{{ item }}"
      permanent: true
      state: enabled
      immediate: true
    loop:
      - 9200/tcp
      - 9300/tcp
      - 5601/tcp
  - name: selinux port open
    seport:
      ports: "{{ item }}"
      proto: tcp
      setype: http_port_t
      state: present
    loop:
      - 9200
      - 9300
      - 5601
  - name: reload systemd
    shell: 'systemctl daemon-reload'
  - name: start and enable packages
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    loop:
      - elasticsearch
      - kibana
      - firewalld

- name: configure elasticsearch/kibana
  hosts: localhost
  vars:
    kibana:
      - path: /etc/kibana/kibana.yml
        regex: '^#server.host:'
        line: "server.host: {{ ansible_default_ipv4['address'] }}"
      - path: /etc/kibana/kibana.yml
        regex: '^#server.port:'
        line: "server.port: 5601"
    elastic:
      - path: /etc/elasticsearch/elasticsearch.yml
        regex: '^#network.host:'
        line: "network.host: {{ ansible_default_ipv4['address'] }}"
      - path: /etc/elasticsearch/elasticsearch.yml
        regex: '^#http.port:'
        line: "http.port: 9200"
  tasks:
  
  - name: edit config files
    lineinfile:
      path: "{{ item.path }}"
      regex: "{{ item.regex }}"
      line: "{{ item.line }}"
    loop: "{{ elastic + kibana }}"
  
  - name: create elastic token for kibana
    shell: '/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token --scope kibana > enrollment_token'
  
  - name: Set password for elastic user
    shell: "/usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic --batch"
    register: password_result

  - name: password_result
    copy:
      content: "{{ password_result.stdout_lines[1] }}\n"
      dest: ./password_result

  - name: restart services
    service:
      name: "{{ item }}"
      state: restarted
    loop:
      - elasticsearch
      - kibana    
