---
- name: enroll agents
  hosts: agents
  tasks:
  - name: retrieve enrollment_api_keys
    shell: |
      curl -X GET "{{ hostvars['localhost']['ansible_host'] }}:5601/api/fleet/enrollment_api_keys" -H "kbn-xsrf: true" -H "Content-Type: application/json" -u elastic:{{ lookup('file', '/root/elastic_labs/password_result') }}
    register: output
  - name: extract output
    set_fact:
      parsed_output: "{{ output.stdout_lines[0] | from_json }}"
  - name: extract api key
    set_fact:
      api_key: "{{ parsed_output.list[1].api_key }}"
  - name: check if elastic agent is installed
    stat:
      path: /usr/bin/elastic-agent
    register: elastic_agent_installed
  - name: download elastic agent
    shell: "{{ item }}"
    loop:
      - curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.15.3-linux-x86_64.tar.gz
      - tar xzvf elastic-agent-8.15.3-linux-x86_64.tar.gz
    when: not elastic_agent_installed.stat.exists
  
  
  
   - cd elastic-agent-8.15.3-linux-x86_64
        - "echo 'Y' | sudo ./elastic-agent install --url=http://{{ hostvars['node1']['ansible_host'] }}:8220 --enrollment-token={{ api_key }} --insecure"
  
  
  
  
  
  
  
  
  
  - name: output enrollment response
    debug:
      var: enrollment_response
  - name: start elastic Agent
    systemd:
      name: elastic-agent
      state: started
      enabled: yes
  - name: verify elastic agent status
    command: elastic-agent status
    register: agent_status
  - name: output elastic agent status
    debug:
      var: agent_status.stdout

