---
- name: add fleet server
  hosts: all
  tasks:
  - name: generate service token
    shell: "/usr/share/elasticsearch/bin/elasticsearch-service-tokens create elastic/fleet-server fleet-token"
    when: inventory_hostname in groups['local']
    register: output

  - name: cat service token to file
    copy:
      content: "{{ output.stdout }}"
      dest: ./fleet_service_token
    when: inventory_hostname in groups['local']

  - name: edit token file
    shell: "sed 's/^.*= //' fleet_service_token"
    when: inventory_hostname in groups['local']
    register: fleet_service_token

  - name: generate enrollment token
    shell: '/usr/share/elasticsearch/bin/elasticsearch-create-enrollment-token --scope node'
    when: inventory_hostname in groups['local']
    register: enroll

  - name: cat enrollment token to file 
    copy:
      content: "{{ enroll.stdout_lines[0] }}"
      dest: ./fleet_enroll_token
    when: inventory_hostname in groups['local']
  
  - name: register enrollment token
    shell: 'cat ./fleet_enroll_token'
    when: inventory_hostname in groups['local']
    register: fleet_enroll_token

  - name: debug
    debug:
      var: fleet_enroll_token.stdout
    when: inventory_hostname in groups['local']
  - name: debug1
    debug:
      var: fleet_service_token.stdout
    when: inventory_hostname in groups['local']
   


  - name: install fleet server on node1
    shell: |
      curl -L -O https://artifacts.elastic.co/downloads/beats/elastic-agent/elastic-agent-8.15.3-linux-x86_64.tar.gz
      tar xzvf elastic-agent-8.15.3-linux-x86_64.tar.gz
      cd elastic-agent-8.15.3-linux-x86_64 && \
      echo 'y' | sudo ./elastic-agent install \
      --fleet-server-es=https://{{ hostvars['node1']['ansible_host'] }}:9200 \
      --fleet-server-service-token={{ fleet_service_token }} \
      --fleet-server-policy=fleet-server-policy \
      --fleet-server-port=8220 \
      --insecure
    when: inventory_hostname in groups['fleet']
