---
- name: create root ssh keys
  hosts: all 
  tasks:

  - name: Ensure SSH root login is enabled
    lineinfile:
      path: /etc/ssh/sshd_config
      state: present
      regex: "{{ item.regex }}"
      line: "{{ item.line }}"
    loop:
      - regex: '^PermitRootLogin'
        line: 'PermitRootLogin yes'
      - regex: '^PasswordAuthentication'
        line: 'PasswordAuthentication no'
      - regex: '^PubkeyAuthentication'
        line: 'PubkeyAuthentication yes'

  - name: Restart SSH service
    service:
      name: sshd
      state: restarted

  - name: Generate root SSH keypair with the default values and no passphrase for control
    community.crypto.openssh_keypair:
      path: /root/.ssh/id_rsa
      owner: root
      group: root
    when: inventory_hostname in groups['local']

  - name: copy control root public key to nodes
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
    when: inventory_hostname in groups['nodes']

  - name: generate /etc/hosts file with template
    template:
      src: ./etc_hosts.j2
      dest: /etc/hosts

  - name: toggle off ask_pass
    lineinfile:
      path: /home/ansible/elastic_labs/ansible.cfg
      regex: '^ask_pass'
      line: ask_pass=false
    when: inventory_hostname in groups['local']
