---
- name: setup repo client
  hosts: nodes
  tasks:
  - name: create repo on nodes
    yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      baseurl: "{{ item.baseurl }}"
      gpgcheck: "{{ item.gpgcheck }}"
    when: ansible_os_family == 'RedHat'
    loop:
      - name: AppStream
        description: AppStream-rhel-repo
        baseurl: ftp://control.streetrack.org/AppStream
        gpgcheck: no
      - name: BaseOS
        description: BaseOS-rhel-repo
        baseurl: ftp://control.streetrack.org/BaseOS
        gpgcheck: no
  - name: confirm python installed
    yum:
      name: python3
      state: present
    when: ansible_os_family == 'RedHat'

