---
- name: setup zeek on fleet server
  hosts: fleet
  tasks:
  - name: install zeek 6.0
    apt:
      name: zeek-6.0
      state: present
  - name: export PATH environment variable
    lineinfile:
      path: "{{ item }}"
      line: 'export PATH=/opt/zeek/bin:$PATH'
    loop:
      - /root/.bashrc
      - /home/ansible/.bashrc
  - name: ensure ufw is installed
    apt:
      name: "{{ item }}"
      state: present
    loop:
      - ufw
      - sshpass
  - name: open ports on firewall
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    loop:
      - 22
      - 47760
      - 8220
  - name: enable ufw
    shell: "echo 'y' | ufw enable"
  - name: start and enable ufw
    service:
      name: ufw
      state: restarted
      enabled: true
  - name: create .ssh directory for root user
    file:
      path: /root/.ssh
      state: directory
      owner: root
      group: root
      mode: '0700'
  - name: Generate root SSH keypair with the default values and no passphrase
    community.crypto.openssh_keypair:
      path: /root/.ssh/id_rsa
      owner: root
      group: root
  - name:  fetch fleet public key
    fetch:
      src: /root/.ssh/id_rsa.pub
      dest: ./id_rsa.pub
      flat: true

- name: edit zeek configurations
  hosts: all
  tasks:
  - name: copy fleet public key to nodes
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/home/ansible/elastic_labs/id_rsa.pub') }}"
    when: inventory_hostname != 'fleet'
  - name: configure zeek worker nodes
    template:
      src: ./zeek_nodes.j2
      dest: /opt/zeek/etc/node.cfg
    when: inventory_hostname in groups['fleet']
  - name: configure networks.cfg
    lineinfile:
      path: /opt/zeek/etc/networks.cfg
      line: "{{ hostvars['localhost']['ansible_host'] }}/27"
    when: inventory_hostname in groups['fleet']
