---
- name: setup repo client
  hosts: fleet agents attacker
  tasks:
  - name: create repo on nodes
    yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      baseurl: "{{ item.baseurl }}"
      gpgcheck: "{{ item.gpgcheck }}"
    when: ansible_os_family == 'RedHat'
    loop:
      - name: AppStream
        description: AppStream-rhel-repo
        baseurl: ftp://control.streetrack.org/AppStream
        gpgcheck: no
      - name: BaseOS
        description: BaseOS-rhel-repo
        baseurl: ftp://control.streetrack.org/BaseOS
        gpgcheck: no
  - name: confirm python installed
    yum:
      name: python
      state: present
    when: ansible_os_family == 'RedHat'


  - name: add zeek gpg key
    apt_key:
      url: 'https://download.opensuse.org/repositories/security:zeek/xUbuntu_22.04/Release.key'
      state: present
    when: ansible_os_family == 'Debian'
  - name: add zeek repo
    apt_repository:
      repo: 'deb http://download.opensuse.org/repositories/security:/zeek/xUbuntu_22.04/ /'
      state: present
    when: ansible_os_family == 'Debian'
  - name: update and upgade packages on ubuntu
    apt:
      update_cache: true
      upgrade: dist
    when: ansible_os_family == 'Debian'
  - name: confirm python installed
    apt:
      name: python3
      state: present
    when: ansible_os_family == 'Debian'
