---
- name: setup repo client
  hosts: nodes
  tasks:
  - name: create repo on nodes
    yum_repository:
      name: "{{ item.name }}"
      description: "{{ item.description }}"
      baseurl: "{{ item.baseurl }}"
      gpgcheck: "{{ item.gpgcheck }}"
    when: ansible_os_family == 'RedHat'
    loop:
      - name: AppStream
        description: AppStream-rhel-repo
        baseurl: ftp://control.streetrack.org/AppStream
        gpgcheck: no
      - name: BaseOS
        description: BaseOS-rhel-repo
        baseurl: ftp://control.streetrack.org/BaseOS
        gpgcheck: no
  - name: confirm python installed
    yum:
      name: python
      state: present
    when: ansible_os_family == 'RedHat'

- name: install zeek on rhel 9 using centos 8 repo
  hosts: all
  tasks:
  - name: install required dependencies
    yum:
      name:
        - cmake
        - make
        - gcc
        - gcc-c++
        - flex
        - bison
        - libpcap-devel
        - openssl-devel
        - python3
        - python3-devel
        - swig
        - zlib-devel
      state: present

  - name: add zeek repository
    yum_repository:
      name: zeek
      description: Zeek
      baseurl: https://download.opensuse.org/repositories/security:/zeek/CentOS_8/
      gpgcheck: yes
      gpgkey: https://download.opensuse.org/repositories/security:/zeek/CentOS_8/Release.key
      enabled: yes

  - name: install zeek
    yum:
      name: zeek
      state: present

