---
- name: shutdown nodes
  hosts: node1 node2 node3
  tasks:
  - name: shutdown node1
    community.general.shutdown:  
      delay: 1
    when: inventory_hostname in groups['attacker']

  - name: shutdown node2
    community.general.shutdown:  
      delay: 4
    when: inventory_hostname in groups['agents']

  - name: shutdown
    community.general.shutdown:  
      delay: 7
    when: inventory_hostname in groups['fleet']
