---
- name: shutdown nodes
  hosts: node1 node2 node3
  tasks:
  - name: shutdown node1
    community.general.shutdown:  
      delay: 1
    when: ansible_hostname == "node1"

  - name: shutdown node2
    community.general.shutdown:  
      delay: 4
    when: ansible_hostname == "node2"

  - name: shutdown
    community.general.shutdown:  
      delay: 7
    when: ansible_hostname == "node3"
