---
- name: Set up Zeek Cluster
  hosts: nodes
  tasks:
        
  - name: Install libpcap (required for packet capture)
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - libpcap
      - openssl
      - zlib
      - python3

  - name: Open Zeek ports (47760-47762)
    firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    loop:
      - 47760
      - 47761
      - 47762

  - name: Ensure SSH is allowed
    firewalld:
      service: ssh
      permanent: yes
      state: enabled
      immediate: yes

  - name: Reload firewalld
    service:
      name: firewalld
      state: restarted

  - name: Download Zeek tarball from GitHub Releases
    get_url:
      url: https://github.com/thuynh808/elastic_labs/releases/download/v1.0.0/zeek-6.0.0.tar.gz
      dest: /tmp/zeek-6.0.0.tar.gz

  - name: Extract Zeek tarball to /usr/local
    unarchive:
      src: /tmp/zeek-6.0.0.tar.gz
      dest: /usr/local
      remote_src: yes
      creates: /usr/local/zeek/bin/zeek

  - name: Add Zeek to PATH
    lineinfile:
      path: /root/.bashrc
      line: 'export PATH=/usr/local/zeek/bin:$PATH'
      state: present

  - name: Source .bashrc to apply the new path
    shell: source ~/.bashrc

  - name: edit node.cfg
    lineinfile:
      path: /usr/local/zeek/etc/node.cfg
      regex: '^interface='
      line: interface=enp0s3

  - name: edit zeekctl.cfg
    lineinfile:
      path: /usr/local/zeek/etc/zeekctl.cfg
      regex: "{{ item.regex }}"
      line: "{{ item.line }}"
    loop:
      - regex: '^MailConnectionSummary'
        line: "MailConnectionSummary = 0"
      - regex: '^MinDiskSpace'
        line: "MinDiskSpace = 0"
      - regex: '^MailHostUpDown'
        line: "MailHostUpDown = 0"

  - name: create systemd service for zeek
    copy:
      content: |
        [Unit]
        Description=Zeek Network Security Monitor
        After=network.target

        [Service]
        Type=forking
        ExecStart=/usr/local/zeek/bin/zeekctl start
        ExecStop=/usr/local/zeek/bin/zeekctl stop
        ExecReload=/usr/local/zeek/bin/zeekctl deploy
        Restart=on-failure
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
      dest: /etc/systemd/system/zeek.service
  
  - name: enable zeek
    service:
      name: zeek.service
      state: reloaded
      enabled: true
      
  - name: start zeek
    shell: 'zeekctl start'
