---
- name: Set up Zeek Cluster
  hosts: nodes
  tasks:
  - name: Install libpcap (required for packet capture)
    yum:
      name: "{{ item }}"
      state: present
    loop:
      - libpcap
      - openssl
      - zlib
      - python3

  - name: Open Zeek ports (47760-47762)
    firewalld:
      port: "{{ item }}/tcp"
      permanent: yes
      state: enabled
      immediate: yes
    loop:
      - 47760
      - 47761
      - 47762

  - name: Ensure SSH is allowed
    firewalld:
      service: ssh
      permanent: yes
      state: enabled
      immediate: yes

  - name: Reload firewalld
    service:
      name: firewalld
      state: restarted

  - name: Download Zeek tarball from GitHub Releases
    get_url:
      url: https://github.com/thuynh808/elastic_labs/releases/download/v1.0.0/zeek-6.0.0.tar.gz
      dest: /tmp/zeek-6.0.0.tar.gz

  - name: Extract Zeek tarball to /usr/local
    unarchive:
      src: /tmp/zeek-6.0.0.tar.gz
      dest: /usr/local
      remote_src: yes
      creates: /usr/local/zeek/bin/zeek

  - name: Add Zeek to PATH
    lineinfile:
      path: /root/.bashrc
      line: 'export PATH=/usr/local/zeek/bin:$PATH'
      state: present

  - name: Source .bashrc to apply the new path
    shell: source ~/.bashrc

